### ISSUE TITLE
Rate limits are sometimes hit on our unauthenticated GitHub API requests

### ISSUE THREAD

**Issue by jameshadfield** [nextstrain/nextstrain.org#93]
E.g. loading https://nextstrain.org/community/grubaughlab/powassan-genomics used to display a list of datasets / narratives in that repo but no longer does. Could be an auspice issue.

![image](https://user-images.githubusercontent.com/8350992/73147033-6a80c300-411a-11ea-8fd5-8cafd9be876a.png)

**Comment by jameshadfield** [comment]
This error (I believe) is due to us making too many requests to GitHub's API, resulting in errors (printed in server logs).

#95 removes the red error banner, which shouldn't be there.

**Comment by jameshadfield** [comment]
Fixed by https://github.com/nextstrain/auspice/commit/e9ff4cbe17ceb347c01dc6fb2384b809bac9a651 - will close once nextstrain.org uses this version of auspice

**Comment by jameshadfield** [comment]
Following on from conversations in slack + #107, as we grow to having over 60 GitHub API requests per hour (requests which are used to list datasets / narratives for community pages) we need to implement some form of server-github auth. 

The simplest method seems to be to create a github user & add credentials to the server, analogous to how we currently have IAM credentials stored on the server for AWS authz.

Not immediately urgent, as #107 should help a lot in the short term.

**Comment by funmu** [comment]
Today when I looked at this issue and the specific page, it worked well for simpler loads. 
Perhaps with load there is a rate limit on github API access that kicks in and puts up an error. 

![image](https://user-images.githubusercontent.com/15069550/76154653-e9133d80-6094-11ea-98a8-d4cd5f127735.png)

**Comment by tsibley** [comment]
@funmu Thanks for looking at this. #107 went a long way to avoiding the API rate limits even under load. I think the issue is still open because ideally we'd still switch to authenticated API access, but it's not urgent to do so.

**Comment by tsibley** [comment]
Noting that this is still an issue from time to time and will only become more so as Community on GitHub is used more.

I see a solution of two parts which can be implemented independently or together (even better):

1. Switch to authenticated API requests so we get a much higher rate limit applied.

    We can [mint a new access token](https://github.com/settings/tokens/new) specifically for nextstrain.org's use on our existing the @nextstrain-bot service/machine user. I believe if the access token has **no permission scopes applied**, then it just gets normal public access levels, which is what we'd want. If not, we'll need a separate service/machine user or a proper [integration "app"](https://github.com/settings/apps). 

2. Switch from simple `fetch()`es to an API client that does dynamic throttling to respect the rate limits. Octokit does a great job of making this easy, [for example](https://github.com/nextstrain/community-search/blob/ce1a4146878e8336c442a175033ad242621f5a17/find#L2-L25).

    Complications with using Octokit include figuring out how to incorporate our current caching, or an equivalent. Caching is an important part of reducing these requests.

    Another complication is how long to retry before returning a 500 error to the nextstrain.org request; the example above retries indefinitely, but that's likely not what we want for nextstrain.org.

**Comment by tsibley** [comment]
I've implemented my first suggestion above as #445 and made a new issue describing my second suggestion as #446.
